// Renders the phone page's icons from assets/branding/shire-logo-transparent.png:
// the mark centered on an opaque warm-ivory square, because iOS fills transparent icon areas with black.
// Usage: swift scripts/make-phone-icons.swift   (writes Sources/ShireCore/Phone/PhoneIcons.swift)
import AppKit

let source = NSImage(contentsOfFile: "assets/branding/shire-logo-transparent.png")!
func png(size: Int, inset: Double) -> Data {
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: size, pixelsHigh: size, bitsPerSample: 8, samplesPerPixel: 4,
                               hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    NSColor(srgbRed: 0.965, green: 0.945, blue: 0.9, alpha: 1).setFill()
    NSRect(x: 0, y: 0, width: size, height: size).fill()
    let pad = Double(size) * inset
    source.draw(in: NSRect(x: pad, y: pad, width: Double(size) - 2 * pad, height: Double(size) - 2 * pad),
                from: .zero, operation: .sourceOver, fraction: 1)
    NSGraphicsContext.restoreGraphicsState()
    return rep.representation(using: .png, properties: [:])!
}
let touch = png(size: 180, inset: 0.04).base64EncodedString()
let large = png(size: 512, inset: 0.04).base64EncodedString()
let swift = """
// Generated by scripts/make-phone-icons.swift from assets/branding/shire-logo-transparent.png. Don't edit by hand.
import Foundation

extension PhonePage {
    /// 180×180 Home Screen icon (iOS `apple-touch-icon`).
    static let touchIconPNG = Data(base64Encoded: "\(touch)")!
    /// 512×512 icon for the web app manifest.
    static let largeIconPNG = Data(base64Encoded: "\(large)")!
}

"""
try! swift.write(toFile: "Sources/ShireCore/Phone/PhoneIcons.swift", atomically: true, encoding: .utf8)
print("wrote Sources/ShireCore/Phone/PhoneIcons.swift (\(touch.count + large.count) base64 chars)")
